---
- name: install java
  yum: name=java-1.7.0-oracle-devel state=present
- name: install play framework
  unarchive: src=http://downloads.typesafe.com/play/2.2.2/play-2.2.2.zip dest=/opt/ creates=/opt/play-2.2.2/play  
- name: create symlink
  file: src=/opt/play-2.2.2/ path=/opt/play state=link

  
  